apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: 2021-03-10T19:46:46Z
  labels:
    app: codestatebkenddep
  name: codestatebkenddep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codestatebkenddep
  strategy: {}
  template:
    metadata:
      creationTimestamp: 2021-03-10T19:46:46Z
      labels:
        app: codestatebkenddep
    spec:
      containers:
      - image: cloudlearnall/backend:1.1
        name: codestatebkend
        resources: {}
status: {}
--- 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2021-03-10T19:46:46Z
  labels:
    app: codestatebkenddep
  name: codestatebkenddep
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: codestatebkenddep
  type: ClusterIP
status:
  loadBalancer: {}
