apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: codestatebkenddep
  name: codestatebkenddep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codestatebkenddep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: codestatebkenddep
    spec:
      containers:
      - image: codestatebkend:latest
        name: codestatebkend
        resources: {}
        imagePullPolicy: Never
status: {}
--- 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: codestatebkenddep
  name: codestatebkenddep
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: codestatebkenddep
  type: ClusterIP
status:
  loadBalancer: {}
